spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password: 1234

token:
  expiration_time: 8640000
  secret: secret123@234$521~!sxcb402@!2g2_#change2

gateway:
  ip: 192.168.75.239